apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "amazingscanner.fullname" . }}-config
  labels:
    {{- include "amazingscanner.labels" . | nindent 4 }}
data:
  DOCSCANNER_MODELS: /app/models
  GRADIO_SERVER_NAME: 0.0.0.0
  GRADIO_SERVER_PORT: {{ .Values.service.targetPort | quote }}
  PYTHONUNBUFFERED: "1"
