apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - autoscaling.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: amazingscanner
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false

images:
  - name: ghcr.io/dwin-gharibi/amazingscanner
    newTag: latest
